name: masterhanyu_app
description: "My FYP bruh."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
 
# Third-party dependencies
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  video_player: ^2.8.6
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  audioplayers: ^6.1.0
  confetti: ^0.7.0

# dev_dependencies specify packages needed for development and testing.
# These dependencies are not included in the final build of your application.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
  # images & video #
    - assets/image/logo.png
    - assets/video/cat_typing.mp4
    - assets/image/pinyin.png
    - assets/image/greetings.png
    - assets/image/finish1.png
    - assets/image/syllable_ba1.png
    - assets/image/ba1.png
    - assets/image/1st_tone.png
    - assets/image/2nd_tone.png
    - assets/image/3rd_tone.png
    - assets/image/4th_tone.png
    - assets/image/friends.png
    - assets/image/name.png
    - assets/image/lvl1_lesson.png
    - assets/image/lvl2_lesson.png
    - assets/image/lvl1_time.png
    - assets/image/lvl2_time.png
    - assets/image/lvl1_quiz.png
    - assets/image/lvl2_quiz.png
    - assets/image/bú_kèqi.png
    - assets/image/duìbuqǐ.png
    - assets/image/hǎojiǔ_bújiàn.png
    - assets/image/méi_guānxi.png
    - assets/image/nǐhǎo.png
    - assets/image/nǐhǎo_ma.png
    - assets/image/wǎn_ān.png
    - assets/image/zàijiàn.png
    - assets/image/wǎnshang_hǎo.png
    - assets/image/wǒ_hěn_hǎo.png
    - assets/image/wǒ_jiào.png
    - assets/image/wǒ_shì.png
    - assets/image/wǔ_ān.png
    - assets/image/xièxie.png
    - assets/image/zàijiàn.png
    - assets/image/zǎo_ān.png


  # audio syllable #
    - assets/audio/syllable/ba.mp3
    - assets/audio/syllable/mao.mp3
    - assets/audio/syllable/ne.mp3
    - assets/audio/syllable/teng.mp3
    - assets/audio/syllable/hou.mp3
    - assets/audio/syllable/kong.mp3
    - assets/audio/syllable/qi.mp3
    - assets/audio/syllable/jia.mp3
    - assets/audio/syllable/qiao.mp3
    - assets/audio/syllable/jian.mp3
    - assets/audio/syllable/niu.mp3
    - assets/audio/syllable/yin.mp3
    - assets/audio/syllable/xiong.mp3
    - assets/audio/syllable/wu.mp3
    - assets/audio/syllable/zhua.mp3
    - assets/audio/syllable/shuai.mp3
    - assets/audio/syllable/zuan.mp3
    - assets/audio/syllable/chuang.mp3
    - assets/audio/syllable/cuo.mp3
    - assets/audio/syllable/sun.mp3
    - assets/audio/syllable/ju.mp3
    - assets/audio/syllable/lüe.mp3
    - assets/audio/syllable/quan.mp3
    - assets/audio/syllable/yun.mp3
    - assets/audio/syllable/dang.mp3
    - assets/audio/syllable/die.mp3
    - assets/audio/syllable/er.mp3
    - assets/audio/syllable/fan.mp3
    - assets/audio/syllable/gen.mp3
    - assets/audio/syllable/lei.mp3
    - assets/audio/syllable/mo.mp3
    - assets/audio/syllable/pai.mp3
    - assets/audio/syllable/qing.mp3
    - assets/audio/syllable/xiang.mp3
    - assets/audio/syllable/rui.mp3

  # audio pinyin initials #
    - assets/audio/initial/b.mp3
    - assets/audio/initial/c.mp3
    - assets/audio/initial/ch.mp3
    - assets/audio/initial/d.mp3
    - assets/audio/initial/f.mp3
    - assets/audio/initial/g.mp3
    - assets/audio/initial/h.mp3
    - assets/audio/initial/j.mp3
    - assets/audio/initial/k.mp3
    - assets/audio/initial/l.mp3
    - assets/audio/initial/m.mp3
    - assets/audio/initial/n.mp3
    - assets/audio/initial/p.mp3
    - assets/audio/initial/q.mp3
    - assets/audio/initial/r.mp3
    - assets/audio/initial/s.mp3
    - assets/audio/initial/sh.mp3
    - assets/audio/initial/t.mp3
    - assets/audio/initial/w.mp3
    - assets/audio/initial/x.mp3
    - assets/audio/initial/y.mp3
    - assets/audio/initial/z.mp3
    - assets/audio/initial/zh.mp3

  # audio pinyin finals #
    - assets/audio/final/a.mp3
    - assets/audio/final/ai.mp3
    - assets/audio/final/an.mp3
    - assets/audio/final/ang.mp3
    - assets/audio/final/ao.mp3
    - assets/audio/final/e.mp3
    - assets/audio/final/ei.mp3
    - assets/audio/final/en.mp3
    - assets/audio/final/eng.mp3
    - assets/audio/final/er.mp3
    - assets/audio/final/i.mp3
    - assets/audio/final/ia.mp3
    - assets/audio/final/ian.mp3
    - assets/audio/final/iang.mp3
    - assets/audio/final/iao.mp3
    - assets/audio/final/ie.mp3
    - assets/audio/final/in.mp3
    - assets/audio/final/ing.mp3
    - assets/audio/final/iong.mp3
    - assets/audio/final/iu.mp3
    - assets/audio/final/o.mp3
    - assets/audio/final/ou.mp3
    - assets/audio/final/ong.mp3
    - assets/audio/final/u.mp3
    - assets/audio/final/ua.mp3
    - assets/audio/final/uai.mp3
    - assets/audio/final/uan.mp3
    - assets/audio/final/uang.mp3
    - assets/audio/final/ui.mp3
    - assets/audio/final/un.mp3
    - assets/audio/final/uo.mp3
    - assets/audio/final/ü.mp3
    - assets/audio/final/üan.mp3
    - assets/audio/final/üe.mp3
    - assets/audio/final/ün.mp3
  
 # audio tones #
    - assets/audio/tones/1st_ā.mp3
    - assets/audio/tones/2nd_á.mp3
    - assets/audio/tones/3rd_ǎ.mp3
    - assets/audio/tones/4th_à.mp3
    - assets/audio/tones/a.mp3
    - assets/audio/tones/1st_duō.mp3
    - assets/audio/tones/1st_zī.mp3
    - assets/audio/tones/2nd_ú.mp3
    - assets/audio/tones/3rd_fǎ.mp3
    - assets/audio/tones/3rd_ǐ.mp3
    - assets/audio/tones/4th_gù.mp3
    - assets/audio/tones/4th_wò.mp3
    - assets/audio/tones/4th_xiè.mp3

 # audio intro_quiz #
    - assets/audio/intro_quiz/1st_bēn.mp3
    - assets/audio/intro_quiz/1st_cūn.mp3
    - assets/audio/intro_quiz/1st_huān.mp3
    - assets/audio/intro_quiz/1st_xiāng.mp3
    - assets/audio/intro_quiz/1st_xūn.mp3
    - assets/audio/intro_quiz/1st_zhuāng.mp3
    - assets/audio/intro_quiz/2nd_chóu.mp3
    - assets/audio/intro_quiz/2nd_qié.mp3
    - assets/audio/intro_quiz/2nd_shá.mp3
    - assets/audio/intro_quiz/2nd_shén.mp3
    - assets/audio/intro_quiz/2nd_sóng.mp3
    - assets/audio/intro_quiz/2nd_xióng.mp3
    - assets/audio/intro_quiz/2nd_zhuó.mp3
    - assets/audio/intro_quiz/3rd_fǎng.mp3
    - assets/audio/intro_quiz/3rd_liǎng.mp3
    - assets/audio/intro_quiz/3rd_qǐng.mp3
    - assets/audio/intro_quiz/3rd_wǒ.mp3
    - assets/audio/intro_quiz/4th_gùn.mp3
    - assets/audio/intro_quiz/4th_lèi.mp3
    - assets/audio/intro_quiz/4th_què.mp3
    - assets/audio/intro_quiz/4th_ruì.mp3
    - assets/audio/intro_quiz/4th_zuì.mp3

    # audio greetings #
    - assets/audio/greetings/nǐhǎo.mp3
    - assets/audio/greetings/nǐhǎo_ma.mp3
    - assets/audio/greetings/wǒ_shì.mp3
    - assets/audio/greetings/wǒ_jiào.mp3
    - assets/audio/greetings/wǒ_hěn_hǎo.mp3
    - assets/audio/greetings/zǎo_ān.mp3
    - assets/audio/greetings/wǔ_ān.mp3
    - assets/audio/greetings/wǎn_ān.mp3
    - assets/audio/greetings/xièxie.mp3
    - assets/audio/greetings/bú_kèqi.mp3
    - assets/audio/greetings/duìbuqǐ.mp3
    - assets/audio/greetings/hǎojiǔ_bújiàn.mp3
    - assets/audio/greetings/méi_guānxi.mp3
    - assets/audio/greetings/zàijiàn.mp3
    - assets/audio/greetings/wǎnshang_hǎo.mp3

  # audio #
    - assets/audio/finish.mp3
    - assets/audio/correct.mp3
    - assets/audio/wrong.mp3

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
